name = 'continuous_threading'
version = '1.1.1'
description = 'Library to help manage threads that run continuously for a long time.'
url = 'https://github.com/justengel/continuous_threading'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
